# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.
This version injects default CLI args when run without arguments and randomizes the MuJoCo cube
position uniformly in:
  x in [0.18, 0.30], y in [-0.15, 0.15], z = 0.015 (on plane)
BEFORE each episode begins (including the first), without modifying the robot class.
It also enforces that the sampled cube position is at least 5 cm away from the end-goal
point (0.2, -0.15, 0.005) in the XY plane.
"""

import logging
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from pprint import pformat
from contextlib import nullcontext

import numpy as np
import mujoco  # to manipulate the sim directly

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.utils import build_dataset_frame, hw_to_dataset_features
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so100_follower,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
)
# Ensure Mujoco sim follower type is registered (import side-effect)
from lerobot.robots import so101_follower_mj  # noqa: F401

from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import _init_rerun, log_rerun_data


# -------------------------
# MuJoCo cube randomization
# -------------------------

def randomize_cube_xy_in_sim(
    robot: Robot,
    body_name: str = "cube_body",
    x_range: tuple[float, float] = (0.18, 0.30),
    y_range: tuple[float, float] = (-0.15, 0.15),
    z: float = 0.015,
    settle_steps: int = 5,
    avoid_target_xy: tuple[float, float] | None = None,
    min_dist_from_target: float = 0.0,
    max_tries: int = 100,
) -> tuple[float, float, float] | None:
    """
    Randomly place the cube body uniformly within the XY ranges at fixed height z, orientation identity.
    This directly writes qpos for the free joint attached to `body_name`, then calls mj_forward and a few mj_step.

    If `avoid_target_xy` is provided together with `min_dist_from_target > 0`,
    the sampled (x, y) will be at least `min_dist_from_target` away from that point in the XY plane.

    Returns:
        (x, y, z) if successful, else None (with a warning).
    """
    # We only proceed if we have direct access to MuJoCo model/data on this robot
    model = getattr(robot, "model", None)
    data = getattr(robot, "data", None)
    if model is None or data is None:
        logging.warning("Randomize skipped: robot model/data not available (robot type: %s).", getattr(robot, "name", type(robot).__name__))
        return None

    # Find body id by name
    b_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, body_name)
    if b_id < 0:
        logging.warning("Randomize skipped: body '%s' not found in model.", body_name)
        return None

    # Get the first joint of this body, ensure it is FREE joint
    j_adr = int(model.body_jntadr[b_id])
    j_num = int(model.body_jntnum[b_id])
    if j_num < 1:
        logging.warning("Randomize skipped: body '%s' has no joints (expected a free joint).", body_name)
        return None

    j_id = j_adr  # first joint
    j_type = int(model.jnt_type[j_id])
    if j_type != int(mujoco.mjtJoint.mjJNT_FREE):
        logging.warning("Randomize skipped: first joint of body '%s' is not FREE.", body_name)
        return None

    # Rejection sample x,y uniformly; set identity orientation
    x = y = None
    need_avoid = avoid_target_xy is not None and min_dist_from_target > 0.0
    min_d2 = min_dist_from_target * min_dist_from_target
    for _ in range(max_tries):
        x_try = float(np.random.uniform(*x_range))
        y_try = float(np.random.uniform(*y_range))
        if need_avoid:
            dx = x_try - float(avoid_target_xy[0])
            dy = y_try - float(avoid_target_xy[1])
            if (dx * dx + dy * dy) < min_d2:
                continue
        x, y = x_try, y_try
        break

    if x is None or y is None:
        logging.warning(
            "Randomize skipped: could not sample a position >= %.3f m away from target %s within %d tries.",
            min_dist_from_target, avoid_target_xy, max_tries
        )
        return None

    qw, qx, qy, qz = 1.0, 0.0, 0.0, 0.0

    # qpos slice for this joint
    qadr = int(model.jnt_qposadr[j_id])
    data.qpos[qadr : qadr + 7] = [x, y, float(z), qw, qx, qy, qz]

    # Forward kinematics and let the sim settle a few steps
    mujoco.mj_forward(model, data)
    for _ in range(max(0, settle_steps)):
        mujoco.mj_step(model, data)

    logging.info("Randomized cube '%s' to (x=%.3f, y=%.3f, z=%.3f).", body_name, x, y, z)
    return (x, y, float(z))


# -------------------------
# Recording implementation
# -------------------------

@dataclass
class DatasetRecordConfig:
    repo_id: str
    single_task: str
    root: str | Path | None = None
    fps: int = 30
    episode_time_s: int | float = 60
    reset_time_s: int | float = 60
    num_episodes: int = 50
    video: bool = True
    push_to_hub: bool = True
    private: bool = False
    tags: list[str] | None = None
    num_image_writer_processes: int = 0
    num_image_writer_threads_per_camera: int = 4
    video_encoding_batch_size: int = 1

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    teleop: TeleoperatorConfig | None = None
    policy: PreTrainedConfig | None = None
    display_data: bool = False
    play_sounds: bool = True
    resume: bool = False

    def __post_init__(self):
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        return ["policy"]


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so100_leader.SO100Leader,
                        so101_leader.SO101Leader,
                        koch_leader.KochLeader,
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    if policy is not None:
        policy.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        observation = robot.get_observation()

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")

        if policy is not None:
            action_values = predict_action(
                observation_frame,
                policy,
                get_safe_torch_device(policy.config.device),
                policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )
            action = {key: action_values[i].item() for i, key in enumerate(robot.action_features)}
        elif policy is None and isinstance(teleop, Teleoperator):
            action = teleop.get_action()
        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}

            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)

            action = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        sent_action = robot.send_action(action)

        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, sent_action, prefix="action")
            frame = {**observation_frame, **action_frame}
            dataset.add_frame(frame, task=single_task)

        if display_data:
            log_rerun_data(observation, action)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        _init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    action_features = hw_to_dataset_features(robot.action_features, "action", cfg.dataset.video)
    obs_features = hw_to_dataset_features(robot.observation_features, "observation", cfg.dataset.video)
    dataset_features = {**action_features, **obs_features}

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    manager_ctx = VideoEncodingManager(dataset) if cfg.dataset.video else nullcontext()

    with manager_ctx:
        recorded_episodes = 0
        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            # Randomize the cube BEFORE starting to record the episode (also covers the very first episode).
            placed = randomize_cube_xy_in_sim(
                robot=robot,
                body_name="cube_body",          # from your XML
                x_range=(0.18, 0.30),
                y_range=(-0.15, 0.15),
                z=0.015,                        # half of cube size so it rests on the plane
                settle_steps=5,
                avoid_target_xy=(0.2, -0.15),   # end-goal XY
                min_dist_from_target=0.05,      # at least 5 cm away in XY
            )
            if placed is not None:
                x, y, z = placed
                logging.info("Cube randomized to x=%.3f, y=%.3f, z=%.3f before episode start.", x, y, z)
            else:
                logging.warning("Cube randomization skipped or failed before episode.")

            log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop=teleop,
                policy=policy,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
            )

            # Reset window (no recording) to let you reset the arm, etc.
            should_do_reset_window = not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
            )
            if should_do_reset_window:
                log_say("Reset the environment", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                )

            if events["rerecord_episode"]:
                log_say("Re-record episode", cfg.play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                dataset.clear_episode_buffer()
                continue

            dataset.save_episode()
            recorded_episodes += 1

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    record()


if __name__ == "__main__":
    import sys
    # Inject your CLI-equivalent defaults if no args are provided (e.g., when pressing Run)
    if len(sys.argv) == 1:
        sys.argv += [
            "--robot.type=so101_follower_mj",
            "--robot.id=my_sim_follower",
            "--robot.launch_viewer=true",
            "--robot.use_degrees=false",
            '--robot.cameras={"hand_eye": {"type": "mujoco", "name": "handeye", "width": 640, "height": 480, "fps": 30}}',
            "--teleop.type=so101_leader",
            "--teleop.port=your_port",
            "--teleop.id=my_awesome_leader_arm",
            "--display_data=true",
            "--dataset.repo_id=mj2",
            "--dataset.num_episodes=100",
            "--dataset.single_task=Grab the blue cube and place it on the red target",
        ]
    main()