# CNN-Transformer model configuration
_target_: models.cnn_transformer.CNNTransformer
window_size: 500      #if this value is changed, then it must be updated in data config
num_features: 8      # data features length
num_classes: 5      # classes
learning_rate: 0.001
cnn_channels: [64, 128]
transformer:
  encoding: learnable   #learnable or fixed
  d_model: 128
  nhead: 8
  num_layers: 1
  dropout: 0.1