# Training configuration
batch_size: 64
max_epochs: 50
accelerator: "auto"
devices: 1
num_workers: 8
callbacks:
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_acc
    mode: max
    patience: 15
    min_delta: 0.001
  checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_acc
    mode: max
    filename: "ur5_exp#_v#_{epoch:02d}"
    dirpath: "${hydra:runtime.cwd}/models/ur5/ckpts"
    save_top_k: 1
  log_epoch:
    _target_: training_pipeline.LogEpochCallback
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: "${hydra:runtime.cwd}/tb_logs"
  name: "ur5"
