#Usage: python src/training_pipeline.py model=cnn_transformer robot=franka  # Run from project root

defaults:
  - robot: franka
  - training: ${robot}
  - data: ${robot}
  - model: cnn_transformer
  - _self_

hydra:
  run:
    dir: ${hydra:runtime.cwd}/outputs/${robot.robot_type}/training/${now:%Y-%m-%d_%H-%M}